### ISSUE TITLE
GB standard logo goes missing 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-gb#94]
The standard logo link is provided in the output HTML file, but the actual logo is missing. I feel it could have been replaced by subsequent runs too.

**Comment by opoudjis** [comment]
Fixed in isodoc; logo image comes from template population, and was not being postprocessed to data-uri or moved to folder before the template was populated.

Now there is a new problem: images by default in HTML have 100% width (as part of responsive design, recent change), but that needs not to apply to images. Logos in HTML need not to scale to 100%.

**Comment by opoudjis** [comment]
Defined logo images as being of class` .logo`, and applying 100% image width to `img:not(.logo)`.

**Comment by ronaldtse** [comment]
Thanks!
